### ISSUE TITLE
How about -1 instead of _1?

### ISSUE THREAD

**Issue by hoosierEE** [ZippyMagician/ayr#2]
Take this bikeshed comment for what it's worth, but I was thinking how (in my experience) writing negative number literals is common but taking the negative of an array is relatively less common. I know K uses `-` for both, so disambiguation requires a space sometimes.

Since ayr displays results like `-1.23`, how about using `-` to write a negative number?

Examples:
```
     -4
-4
     - 1 2 3 
-1 -2 -3 
     -1 2 3
-1 2 3 
```

**Comment by ZippyMagician** [comment]
I was considering having negative numbers display with `_` by default, as I also found this a little strange. I don't really want to make `-` denote negative numbers however, as I feel as if this would make some code require unnecessary spaces (since `_` is unused for everything else, this has no issue). I'll add a flag to make numbers display the current way they do if I decide to make this change, in case some people prefer `Infinity -3 -Infinity` instead of `_ _3 __`

**Comment by ZippyMagician** [comment]
I agree that it's not as common, but there will be some cases where the space is necessary, and I feel people having to understand that `_` denotes a negative number is an ok sacrifice to make to avoid this.

**Comment by hoosierEE** [comment]
That makes sense, `_` is more consistent than sometimes needing a space after `-`.
